config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :starships
  resources :planets
  resources :films
  get 'search' => "search#index"
  root to:  'films#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = get_all()
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person= get_one(params[:id])
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      # @person = Person.find(params[:id])
      # @person = execute_request("people/#{params[:id]}")
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.fetch(:person, {})
    end

    def get_all()
      puts "get all people"
      query = 
      "{
        allPeople {
          edges {
            node {
              ...personFragment
            }
          }
        }
      }
      
      fragment personFragment on Person {
        id
        name
        # birthYear
        # eyeColor
        # gender
        # hairColor
        # height
        # mass
        # skinColor
        # homeworld {
        #   id
        # }
        # species {
        # }
      }
      "

        

      code, body = execute_request(query)
      puts "body[:data] #{body['data']['allPeople']['edges']}, #{body.class.name}"
      return body['data']['allPeople']['edges']
    end

    def get_one(id)
      puts "get one person id #{id}"
      id = '"'+id+'"'
      query = 
        "{
          person(id: #{id}) {
            ...personFragment
          }
        }
        
        fragment personFragment on Person {
          name
          birthYear
          eyeColor
          gender
          hairColor
          height
          mass
          skinColor
          filmConnection { edges { node { ...filmFragment }}}
          starshipConnection { edges { node { ...starshipFragment }}}
          homeworld {
            id
            name
          }
          species {
            id
            name
          }
        }
        
        fragment filmFragment on Film {
          id
          title
        }
        
        fragment starshipFragment on Starship {
          id
          name
        }
        "
      code, body = execute_request(query)
      puts "body[:data] #{body['data']['person']}, #{body.class.name}"
      return body['data']["person"]
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <%# <th colspan="3"></th> %>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |edge| %>
      <% person= edge['node'] %>
      <tr>
        <td><%= link_to person['name'], person_path(person['id']) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @person['name'] %></h1>

<p>
  <strong>Heigh:</strong>
  <%= @person['height'] %>
</p>


<p>
  <strong>Mass:</strong>
  <%= @person['mass'] %>
</p>

<p>
  <strong>Hair color:</strong>
  <%= @person['hairColor'] %>
</p>

<p>
  <strong>Skin color:</strong>
  <%= @person['skinColor'] %>
</p>

<p>
  <strong>Eye color:</strong>
  <%= @person['eyeColor'] %>
</p>

<p>
  <strong>Birth year:</strong>
  <%= @person['birthYear'] %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @person['gender'] %>
</p>

<p>
  <strong>Homeworld:</strong>
  <%= link_to @person['homeworld']['name'], planet_path(@person['homeworld']['id']) %>
</p>



<p>
  <strong>Films:</strong>
  <% @person['filmConnection']['edges'].each do |film| %>
    <%= link_to film['node']['title'], film_path(film['node']['id']) %>-
  <% end %>
</p>

<p>
  <strong>Starships:</strong>
  <% @person['starshipConnection']['edges'].each do |starship| %>
  
  <%= link_to starship['node']['name'], starship_path(starship['node']['id']) %>-
    <%# <p><%= link_to get_name(starship, 'name'), starship_path(get_id(starship,'starships'))</p> %>
  <% end %>
</p>


<%= link_to 'Back', people_path %>