config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :starships
  resources :planets
  resources :films
  get 'search' => "search#index"
  root to:  'films#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/planet.rb
class Planet < ApplicationRecord
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :set_planet, only: [:show, :edit, :update, :destroy]

  # GET /planets
  # GET /planets.json
  def index
    @planets = get_all()
  end

  # GET /planets/1
  # GET /planets/1.json
  def show
    @planet= get_one(params[:id])
  end

  # GET /planets/new
  def new
    @planet = Planet.new
  end

  # GET /planets/1/edit
  def edit
  end

  # POST /planets
  # POST /planets.json
  def create
    @planet = Planet.new(planet_params)

    respond_to do |format|
      if @planet.save
        format.html { redirect_to @planet, notice: 'Planet was successfully created.' }
        format.json { render :show, status: :created, location: @planet }
      else
        format.html { render :new }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planets/1
  # PATCH/PUT /planets/1.json
  def update
    respond_to do |format|
      if @planet.update(planet_params)
        format.html { redirect_to @planet, notice: 'Planet was successfully updated.' }
        format.json { render :show, status: :ok, location: @planet }
      else
        format.html { render :edit }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planets/1
  # DELETE /planets/1.json
  def destroy
    @planet.destroy
    respond_to do |format|
      format.html { redirect_to planets_url, notice: 'Planet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planet
      # @planet = Planet.find(params[:id])
      # @planet = execute_request("planets/#{params[:id]}")
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def planet_params
      params.fetch(:planet, {})
    end

  def get_all()
    puts "get all planets"
    query = 
    "{
      allPlanets {
        edges {
          node {
            ...planetFragment
          }
        }
      }
    }
    
    fragment planetFragment on Planet {
      id
      name
      # diameter
      # rotationPeriod
      # orbitalPeriod
      # gravity
      # population
      # climates
      # terrains
      # surfaceWater
    }
    
    "

      

    code, body = execute_request(query)
    puts "body[:data] #{body['data']['allPlanets']['edges']}, #{body.class.name}"
    return body['data']['allPlanets']['edges']
  end

  def get_one(id)
    puts "get one person id #{id}"
    id = '"'+id+'"'
    query = 
      "{
        planet(id: #{id}) {
          ...planetFragment
        }
      }
      
      fragment planetFragment on Planet {
        id
        name
        diameter
        rotationPeriod
        orbitalPeriod
        gravity
        population
        climates
        terrains
        surfaceWater
        filmConnection { edges { node { ...filmFragment }}}
        residentConnection {edges {node { ...residentFragment}}}
      }
      fragment filmFragment on Film {
        id
        title
      }
      
      fragment residentFragment on Person {
        id
        name
      }            
      "
    code, body = execute_request(query)
    puts "body[:data] #{body['data']['planet']}, #{body.class.name}"
    return body['data']["planet"]
  end

end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/views/planets/_form.html.erb
<%= form_with(model: planet, local: true) do |form| %>
  <% if planet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(planet.errors.count, "error") %> prohibited this planet from being saved:</h2>

      <ul>
      <% planet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/planets/edit.html.erb
<h1>Editing Planet</h1>

<%= render 'form', planet: @planet %>

<%= link_to 'Show', @planet %> |
<%= link_to 'Back', planets_path %>

app/views/planets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Planets</h1>
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <%# <th colspan="3"></th> %>
    </tr>
  </thead>

  <tbody>
    <% @planets.each do |edge| %>
      <% planet= edge['node'] %>
      <tr>
        <td><%= link_to planet['name'], planet_path(planet['id']) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/planets/new.html.erb
<h1>New Planet</h1>

<%= render 'form', planet: @planet %>

<%= link_to 'Back', planets_path %>

app/views/planets/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @planet['name'] %></h1>

<p>
  <strong>Episode:</strong>
  <%= @planet['rotationPeriod'] %>
</p>

<p>
  <strong>Orbital period:</strong>
  <%= @planet['orbitalPeriod'] %>
</p>

<p>
  <strong>Diameter:</strong>
  <%= @planet['diameter'] %>
</p>

<p>
  <strong>Climate:</strong>
  <%= @planet['climate'] %>
</p>

<p>
  <strong>Gravity:</strong>
  <%= @planet['gravity'] %>
</p>

<p>
  <strong>Terrain:</strong>
  <%= @planet['terrain'] %>
</p>

<p>
  <strong>Surface water:</strong>
  <%= @planet['surfaceWater'] %>
</p>

<p>
  <strong>Population:</strong>
  <%= @planet['population'] %>
</p>

<p>
  <strong>Residents:</strong>
  <% @planet['residentConnection']['edges'].each do |person| %>
    <%= link_to person['node']['name'], person_path(person['node']['id']) %>-
  <% end %>
</p>

<p>
  <strong>Films:</strong>
  <% @planet['filmConnection']['edges'].each do |film| %>
    <%= link_to film['node']['title'], film_path(film['node']['id']) %>-
  <% end %>
</p>


<%= link_to 'Back', planets_path %>