config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :starships
  resources :planets
  resources :films
  get 'search' => "search#index"
  root to:  'films#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/film.rb
class Film < ApplicationRecord
    
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]
  
  # GET /films
  # GET /films.json
  def index
    # @films = Film.all
    @films = get_all()
  end

  # GET /films/1
  # GET /films/1.json
  def show
    @film = get_one(params[:id])
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      # @film = Film.find(params[:id])
      # @film = execute_request("films/#{params[:id]}")
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:name, :year, :director, :productor, :episode)
    end
    
    def get_all()
      query = 
      "{allFilms {
        edges {
          node {
            id
            episodeID
            title
            director
            producers
            releaseDate
          }
        }
      }}"
      code, body = execute_request(query)
      puts "body[:data] #{body['data']['allFilms']['edges']}, #{body.class.name}"
      return body['data']['allFilms']['edges']

      # {"data"=>{"allFilms"=>{"edges"=>
      # response = execute_request("films")
      # response['results'].sort_by { |f| [f['release_date']] }
    end

    def get_one(id)
      puts "get one film id #{id}"
      id = '"'+id+'"'
      query = 
        "{
          film(id: #{id}) {
            ...filmFragment
          }
        }
        
        fragment filmFragment on Film {
          title
          episodeID
          openingCrawl
          director
          producers
          releaseDate
          planetConnection { edges { node { ...planetFragment }}}
          starshipConnection { edges { node { ...starshipFragment }}}
          characterConnection { edges { node { ...characterFragment }}}
        }
        
        fragment planetFragment on Planet {
          id
          name
        }
        
        fragment starshipFragment on Starship {
          id
          name
        }
        
        fragment characterFragment on Person {
          id
          name
        }"
      code, body = execute_request(query)
      puts "body[:data] #{body['data']['film']}, #{body.class.name}"
      return body['data']["film"]

    end
    
    

    # def execute_request(extra)
    #   require 'net/http'
      # require 'json'
    #   uri = URI("#{BASE_URL}/#{extra}")
    #   response = Net::HTTP.get(uri)
    #   JSON.parse(response)
    # end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_form.html.erb
<%= form_with(model: film, local: true) do |form| %>
  <% if film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :film_name %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.date_select :year, id: :film_year %>
  </div>

  <div class="field">
    <%= form.label :director %>
    <%= form.text_field :director, id: :film_director %>
  </div>

  <div class="field">
    <%= form.label :productor %>
    <%= form.text_field :productor, id: :film_productor %>
  </div>

  <div class="field">
    <%= form.label :episode %>
    <%= form.text_field :episode, id: :film_episode %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Films</h1>

<table>
  <thead>
    <tr>
      <th>Episode</th>
      <th>Title</th>
      <th>Year</th>
      <th>Director</th>
      <th>Producers</th>
    </tr>
  </thead>

  <tbody>
    <% @films.each do |edge| %>
      <% film= edge['node'] %>
      <tr>
        <td><%= film['episodeID'] %></td>
        <td><%= link_to film['title'], film_path(film['id']) %> </td>
        <td><%= film['releaseDate'] %></td>
        <td><%= film['director'] %></td>
        <td><%= film['producers'] %></td>
      </tr>
     <% end %>
  </tbody>
</table>

<br>

app/views/films/new.html.erb
<h1>New Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>
<%= puts "film #{@film}" %>
<h1><%= @film['title'] %></h1>

<p>
  <strong>Episode:</strong>
  <%= @film['episodeID'] %>
</p>

<p>
  <strong>Opening crawl:</strong>
  <%= @film['openingCrawl'] %>
</p>

<p>
  <strong>Director:</strong>
  <%= @film['director'] %>
</p>

<p>
  <strong>Producer:</strong>
  <%= @film['producers'] %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @film['releaseDate'] %>
</p>

<p>
  <strong>Characters:</strong>
  <% @film['characterConnection']['edges'].each do |person| %>
    <%= link_to person['node']['name'], person_path(person['node']['id']) %> -
  <% end %>
</p>
 
<p>
  <strong>Planets:</strong>
  <% @film['planetConnection']['edges'].each do |planet| %>
    <%= link_to planet['node']['name'], planet_path(planet['node']['id']) %> -
  <% end %>
</p>

<p>
  <strong>Starships:</strong>
  <% @film['starshipConnection']['edges'].each do |starship| %>
  <%= link_to starship['node']['name'], starship_path(starship['node']['id']) %> -
  <% end %>
</p>

<%= link_to 'Back', films_path %>