config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :starships
  resources :planets
  resources :films
  get 'search' => "search#index"
  root to:  'films#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/starship.rb
class Starship < ApplicationRecord
end

app/controllers/starships_controller.rb
class StarshipsController < ApplicationController
  before_action :set_starship, only: [:show, :edit, :update, :destroy]

  # GET /starships
  # GET /starships.json
  def index
    @starships = get_all()
  end

  # GET /starships/1
  # GET /starships/1.json
  def show
    # puts "id #{params[:id]}"
    @starship= get_one(params[:id])
  end

  # GET /starships/new
  def new
    @starship = Starship.new
  end

  # GET /starships/1/edit
  def edit
  end

  # POST /starships
  # POST /starships.json
  def create
    @starship = Starship.new(starship_params)

    respond_to do |format|
      if @starship.save
        format.html { redirect_to @starship, notice: 'Starship was successfully created.' }
        format.json { render :show, status: :created, location: @starship }
      else
        format.html { render :new }
        format.json { render json: @starship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /starships/1
  # PATCH/PUT /starships/1.json
  def update
    respond_to do |format|
      if @starship.update(starship_params)
        format.html { redirect_to @starship, notice: 'Starship was successfully updated.' }
        format.json { render :show, status: :ok, location: @starship }
      else
        format.html { render :edit }
        format.json { render json: @starship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /starships/1
  # DELETE /starships/1.json
  def destroy
    @starship.destroy
    respond_to do |format|
      format.html { redirect_to starships_url, notice: 'Starship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_starship
      # @starship = Starship.find(params[:id])
      # @starship = execute_request("starships/#{params[:id]}")
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def starship_params
      params.fetch(:starship, {})
    end

    def get_all()
      puts "get all starships"
      query = 
      "{
        allStarships {
          edges {
            node {
              ...starshipFragment
            }
          }
        }
      }
      
      fragment starshipFragment on Starship {
        id
        name
        model
      #   starshipClass
      #   manufacturers
        costInCredits
      #   length
      #   crew
      #   passengers
      #   maxAtmospheringSpeed
      #   hyperdriveRating
      #   MGLT
        cargoCapacity
      #   consumables
      #   pilotConnection { edges { node { ...pilotFragment }}}
      #   filmConnection { edges { node { ...filmFragment }}}
      # }
      # fragment pilotFragment on Person {
      #   name
      # }
      # fragment filmFragment on Film{
      #   title
      }"
      code, body = execute_request(query)
      puts "body[:data] #{body['data']['allStarships']['edges']}, #{body.class.name}"
      return body['data']['allStarships']['edges']
    end

    def get_one(id)
      puts "get one starship id #{id}"
      id = '"'+id+'"'
      query = 
        "{
          starship(id: #{id}) {
            ...starshipFragment
          } 
        }
        
        fragment starshipFragment on Starship {
          id
          name
          model
          starshipClass
          manufacturers
          costInCredits
          length
          crew
          passengers
          maxAtmospheringSpeed
          hyperdriveRating
          MGLT
          cargoCapacity
          consumables
          MGLT
          pilotConnection { edges { node { ...pilotFragment }}}
          filmConnection { edges { node { ...filmFragment }}}
        }
        fragment pilotFragment on Person {
          id
          name
        }
        fragment filmFragment on Film{
          id
          title
        }"
      code, body = execute_request(query)
      puts "body[:data] #{body['data']['starship']}, #{body.class.name}"
      return body['data']["starship"]
  end
end

app/helpers/starships_helper.rb
module StarshipsHelper
end

app/views/starships/_form.html.erb
<%= form_with(model: starship, local: true) do |form| %>
  <% if starship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(starship.errors.count, "error") %> prohibited this starship from being saved:</h2>

      <ul>
      <% starship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/starships/edit.html.erb
<h1>Editing Starship</h1>

<%= render 'form', starship: @starship %>

<%= link_to 'Show', @starship %> |
<%= link_to 'Back', starships_path %>

app/views/starships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Starships</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Model</th>
      <%# <th>Cargo Capacity</th> %>
      <%# <th>Cost In Credits</th> %>
    </tr>
  </thead>

  <tbody>
    <% @starships.each do |edge| %>
      <% starship= edge['node'] %>
      <tr>
        <td><%= link_to starship['name'], starship_path(starship['id']) %></td>
        <td><%= starship['model'] %></td>
        <%# <td><%= starship['cargoCapacity'] %>
        <%# <td><%= starship['costInCredits'] %>
      </tr>
    <% end %>






    <%# <% @starships.each do |starship| %>
      <%# <tr> %>
        <%# <td><%= link_to starship['name'], starship_path(get_id(starship['url'], 'starships')) %>
      <%# </tr> %>
    <%# <% end %> 
  </tbody>
</table>

<br>

app/views/starships/new.html.erb
<h1>New Starship</h1>

<%= render 'form', starship: @starship %>

<%= link_to 'Back', starships_path %>

app/views/starships/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @starship['name'] %></h1>

<p>
  <strong>Model:</strong>
  <%= @starship['model'] %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @starship['manufacturer'] %>
</p>

<p>
  <strong>Cost in credits:</strong>
  <%= @starship['costInCredits'] %>
</p>

<p>
  <strong>Length:</strong>
  <%= @starship['length'] %>
</p>

<p>
  <strong>Max atmosphering speed:</strong>
  <%= @starship['maxAtmospheringSpeed'] %>
</p>

<p>
  <strong>Crew:</strong>
  <%= @starship['crew'] %>
</p>

<p>
  <strong>Passengers:</strong>
  <%= @starship['passengers'] %>
</p>

<p>
  <strong>Cargo capacity:</strong>
  <%= @starship['cargoCapacity'] %>
</p>

<p>
  <strong>Consumables:</strong>
  <%= @starship['consumables'] %>
</p>

<p>
  <strong>Hyperdrive_rating:</strong>
  <%= @starship['hyperdriveRating'] %>
</p>

<p>
  <strong>MGLT:</strong>
  <%= @starship['MGLT'] %>
</p>

<%# <p> %>
  <%# <strong>Starship class:</strong> %>
  <%# <%= @starship['starship_class'] %> 
<%# </p> %>

<p>
  <strong>Pilots:</strong>
  <% @starship['pilotConnection']['edges'].each do |person| %>
    <%= link_to person['node']['name'], person_path(person['node']['id'])%> -
    <%# <p><%= link_to get_name(person, 'name'), person_path(get_id(person,'people')) %>
  <% end %>
</p>

<p>
  <strong>Films:</strong>
  <% @starship['filmConnection']['edges'].each do |film| %>
    <%= link_to film['node']['title'], film_path(film['node']['id'])%> -
  <% end %>
</p>


<%= link_to 'Back', starships_path %>